"""What a tool is, described without naming a provider (Phase 10, M6).

**The vocabulary a model and Orqent share**, and nothing more: a declaration the
model can be shown, a request the model can make, and an implementation Orqent
trusts to run. Nothing here mentions LangChain, Gemini, function declarations, or
JSON-RPC — translating into a provider's tool format is the adapter's job, the
same way it already is for messages (ADR-013).

**Tools are code, exactly as node types are** (ADR-022, by direct analogy). There
is no ``tools`` table, no user-authored schema, and no plugin loader. A workflow
author selects tools *by name* from what the deployment ships; they never
describe one. That removes the entire class of "the author wrote a schema that
does something else" and keeps the trust boundary where ADR-022 put it.

The other half of the analogy matters just as much: because the catalogue is
code, "which tools exist" is a property of the *release*, not of a row. A
published workflow naming a tool means the same thing in every environment.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Mapping
from dataclasses import dataclass, field

from pydantic import BaseModel

from app.domain.errors import AppError
from app.domain.nodes.descriptor import SideEffect

MAX_TOOL_NAME_LENGTH = 64


class ToolError(AppError):
    """A tool could not be run, or should not have been asked for.

    Raised rather than returned so that a failure cannot be mistaken for a
    result — a tool that "returned" its own error message would be handing the
    model a plausible-looking answer, which is the expensive confusion this
    codebase refuses everywhere else (``AgentError``, ``EmbeddingError``,
    ``KnowledgeRetrievalError``).

    The message is written by Orqent and is safe to persist against a run.
    Implementation internals, stack traces, and anything provider-shaped stay
    out of it.
    """

    code = "tool_error"
    http_status = 502

    def __init__(self, message: str, *, retryable: bool = False) -> None:
        super().__init__(message)
        self.retryable = retryable


@dataclass(frozen=True, slots=True)
class ToolCall:
    """One tool invocation **requested by the model**.

    Everything in it is untrusted. The model chose the name and produced the
    arguments, and a provider asserting they match the schema it was given is
    not evidence — it is the same provider's output. Validation happens against
    Orqent's own copy of the schema before anything executes (§9).
    """

    call_id: str
    """The provider's identifier for this request.

    Carried because a single turn may request several tools, and the results
    must be matched back to the requests when the conversation is replayed to
    the model. Opaque to Orqent: it is generated by the provider, echoed back,
    and never interpreted."""

    name: str
    """Which tool the model asked for. **A claim, not a fact** — it is checked
    against the tools this agent was actually allowed before use."""

    arguments: Mapping[str, object] = field(default_factory=dict)
    """What the model wants to pass. Raw, unvalidated, and possibly nonsense."""


@dataclass(frozen=True, slots=True)
class CompletedToolCall:
    """A finished round: what was asked for, and what came back.

    The unit of conversation history the agent port carries. Kept as a pair
    rather than two parallel sequences because a result with no request is
    meaningless and a provider needs them matched to rebuild the exchange.
    """

    call: ToolCall
    result: str
    """The tool's output, already rendered as deterministic text.

    Text, not ``object``: this goes into a model conversation, so it has to be
    serialised eventually, and doing it once at the boundary means the exact
    bytes the model will see are decided in provider-neutral code and are
    assertable in a unit test. See ``app.domain.tools.serialisation``.
    """


class Tool(ABC):
    """One capability an agent may be given."""

    @property
    @abstractmethod
    def definition(self) -> ToolDefinition:
        """What the model is told about this tool."""

    @abstractmethod
    async def execute(self, arguments: BaseModel) -> object:
        """Do the work, and return a JSON-compatible result.

        ``arguments`` has **already been validated** against
        ``definition.parameters`` and is an instance of it, so an implementation
        never parses, coerces, or re-checks — it receives a typed object.

        Asynchronous because a tool that reaches anything will be I/O, and a
        synchronous one would block the event loop the worker shares with every
        other concurrently-executing node (Phase 8 M6).

        Raises :class:`ToolError` when the work cannot be done. Anything else
        escaping is a bug in the tool.
        """


@dataclass(frozen=True, slots=True)
class ToolDefinition:
    """What the model is shown, and what Orqent validates against."""

    name: str
    """Stable, and part of a published workflow forever.

    A workflow stores this string; renaming a tool breaks every version that
    named it, exactly as renaming a node type would. Treated with the same
    append-only discipline."""

    description: str
    """What the tool does, in the model's terms. This is a prompt: it is the
    only thing that makes a model choose this tool over another."""

    parameters: type[BaseModel]
    """The argument schema, as a Pydantic model.

    **Orqent's copy is authoritative.** The same model generates the JSON Schema
    the provider is shown *and* validates what comes back, so the two cannot
    drift — a provider that returns arguments its own schema forbade is caught
    by the same class that produced the schema.

    Pydantic rather than a hand-written JSON Schema dict because it is already
    the project idiom for exactly this pair of jobs (ADR-031, and every node's
    ``config_model``)."""

    side_effect: SideEffect
    """What repeating this tool would do to the outside world (ADR-024).

    Declared per tool rather than inherited from the node, because the node's
    class is about the *model call* — ``ai.agent@1`` is ``AT_LEAST_ONCE`` because
    a retried run pays for the model twice — and says nothing about what a tool
    underneath it touches.

    **M6 executes only ``PURE`` tools, and enforces it** rather than asking
    authors to be careful; see ``ToolRegistry``. Execution is at-least-once
    (ADR-024), so a recovered agent may call the model again, which may request
    the same tool again. For a pure tool that is free. For anything that sends,
    charges, or writes, it is a duplicate — and the machinery that would make
    that safe (idempotency keys threaded to external systems, connections,
    approvals) is deliberately not in this milestone."""

    def json_schema(self) -> dict[str, object]:
        """The argument schema in the shape every provider ultimately wants.

        Generated from ``parameters`` rather than stored beside it, so there is
        exactly one definition of a tool's arguments and no way for the shown
        schema and the enforced schema to disagree.
        """

        return self.parameters.model_json_schema()
