"""Rendering a tool's result as the text a model will read (Phase 10, M6).

Small, pure, and separate because it decides a **contract**: the exact bytes a
model sees after a tool runs. M3 learned this the expensive way one layer up —
``str()`` on a structured input silently made Python's ``repr`` the prompt
format, so a webhook payload reached the model as ``{'order': 7}`` with single
quotes and ``True`` where a model expects ``true``. That was never a decision;
it was what ``str`` happened to do.

The same trap is worse here, because a tool's output is *generated by Orqent* and
a model may be asked to reason over it numerically.
"""

from __future__ import annotations

import json


def render(result: object) -> str:
    """Render a tool result deterministically as JSON text.

    ``sort_keys`` because a model conversation must be reproducible: two runs of
    one published workflow that call the same tool with the same arguments have
    to produce byte-identical turns, and Python's dict ordering is an
    implementation detail of insertion, not a property of the value.

    A bare string is still JSON-encoded, quotes and all. Tempting to pass it
    through unquoted — the prompt renderer one layer up does exactly that — but
    the reason differs: there, the author wrote the string and quoting it would
    change what they wrote. Here the *tool* produced it, and the model is being
    told "this is the tool's return value". Encoding uniformly means ``"7"`` and
    ``7`` stay distinguishable, which is precisely the distinction a model
    reasoning about a calculator result needs.
    """

    return json.dumps(result, ensure_ascii=False, sort_keys=True, default=str)
