"""trigger_registrations — the addressable identity of a webhook trigger

Creates the single Phase 9 M2 table. A row is one webhook address: it names the
trigger node a request should fire, the organization it belongs to, and the
one-way digest of the bearer token that authorises the call.

``token_digest`` stores SHA-256 hex, never the token. The digest is unsalted and
therefore deterministic, which is what makes an indexed equality lookup possible
at all; salting defends low-entropy secrets, and a 256-bit random token is not
one (see ``app.infrastructure.security.token_hashing``). Its UNIQUE constraint is
load-bearing twice: it is the index the receiver's lookup rides (M4), and it is
what stops one token ever addressing two registrations.

The row references a *node* rather than a version or a workflow. The node already
carries both — ``workflow_version_id`` and ``node_type`` — so a second column for
either could only ever disagree with it. Publishing repoints this FK at the new
version's trigger node, which keeps a customer's configured URL stable across a
republish (M3).

Schema-only: no data is seeded, and no lifecycle behaviour exists yet.
Charset/collation are pinned explicitly (``utf8mb4`` / ``utf8mb4_0900_ai_ci``)
rather than inherited from the server default, matching ``0001`` to ``0006`` —
autogenerate omits them every time.

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-18 11:02:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "trigger_registrations",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        # Names the registration to the authoring API; safe to log. Distinct in
        # kind from `token_digest`, which authorises.
        sa.Column("public_id", sa.CHAR(length=26), nullable=False),
        sa.Column("organization_id", mysql.BIGINT(unsigned=True), nullable=False),
        # The trigger node this address fires. Version and kind are read from the
        # node itself rather than copied here.
        sa.Column("workflow_node_id", mysql.BIGINT(unsigned=True), nullable=False),
        # ACTIVE / REVOKED. String rather than a native ENUM, so adding a state
        # later is a code change rather than a migration.
        sa.Column("status", sa.String(length=16), nullable=False),
        # SHA-256 hex of the webhook token. CHAR because the length is fixed.
        sa.Column("token_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_trigger_registrations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        # A workflow that no longer exists has no webhook, and an orphaned
        # registration would be an address resolving to nothing.
        sa.ForeignKeyConstraint(
            ["workflow_node_id"],
            ["workflow_nodes.id"],
            name=op.f("fk_trigger_registrations_workflow_node_id_workflow_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trigger_registrations")),
        sa.UniqueConstraint("public_id", name=op.f("uq_trigger_registrations_public_id")),
        # The receiver's lookup index, and the guarantee that a token addresses
        # at most one registration.
        sa.UniqueConstraint("token_digest", name=op.f("uq_trigger_registrations_token_digest")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_index(
        op.f("ix_trigger_registrations_organization_id"),
        "trigger_registrations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trigger_registrations_workflow_node_id"),
        "trigger_registrations",
        ["workflow_node_id"],
        unique=False,
    )


def downgrade() -> None:
    # DROP TABLE removes the table's own indexes and foreign keys, so the
    # explicit drop_index calls Alembic autogenerated are omitted: on MySQL,
    # dropping an index still backing a foreign key fails ("needed in a foreign
    # key constraint"). Same correction as 0001, 0002, 0004, 0005, and 0006.
    op.drop_table("trigger_registrations")
