"""password_reset_tokens — outstanding password-reset grants, stored hashed

Creates the single AH2 table. A reset token can change a password, so it is
held to the same standard as ``refresh_tokens`` (0002): only a SHA-256 digest is
stored, never the token, and a database leak therefore yields no usable reset
link.

``token_hash`` is unique and is the only key a lookup uses — reset presents a
token and nothing else, so the digest is the entire search key. ``user_id`` is
indexed for supersession, which invalidates every outstanding grant for one user
in a single statement.

Rows are not deleted on use; ``consumed_at`` is set. That is what makes a second
presentation of the same token recognisable as a replay rather than as an
unknown token.

Charset/collation are pinned explicitly (``utf8mb4`` / ``utf8mb4_0900_ai_ci``)
rather than inherited from the server default, matching ``0001`` to ``0009`` —
autogenerate omits them every time.

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-24 23:02:14.834282

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        # SHA-256 hex of the token — never the token. Same width and same
        # reasoning as `refresh_tokens.token_hash`.
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        # NULL means outstanding. Set both when the grant is used and when a
        # newer request supersedes it: "no longer usable" is one state.
        sa.Column("consumed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        # CASCADE: a deleted user must not leave behind a live grant to set a
        # password.
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        # Two rows sharing a digest would make "which grant is this?" ambiguous;
        # with 256 bits of entropy a collision means a bug, not luck.
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_index(
        op.f("ix_password_reset_tokens_expires_at"),
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )


def downgrade() -> None:
    # DROP TABLE removes the table's own indexes and foreign keys, so the
    # explicit drop_index calls Alembic autogenerated are omitted — on MySQL,
    # dropping an index still backing a foreign key fails. Same correction as
    # 0001 to 0009.
    op.drop_table("password_reset_tokens")
