"""schedules — when a schedule-triggered workflow fires next

Creates the single Phase 9 M5 table. A row is one recurring schedule: it names
the ``trigger.schedule@1`` node it fires, the organization it belongs to, and the
next moment it is due.

**The cron expression is deliberately not a column here.** It lives in
``workflow_nodes.config``, frozen into the published version it was authored
into, and the dispatcher reads it back through the node it must join to anyway.
A copy in this table could only ever disagree with the graph about when a
workflow runs. What this table holds is the part that cannot live in an immutable
version because it is rewritten on every dispatch: ``next_run_at``.

**There is no status column.** A schedule is eligible exactly when its node
belongs to the workflow's currently active version and the workflow is not
soft-deleted — both already recorded elsewhere, so a stored flag could only drift
away from them. Removing the schedule trigger and republishing turns it off;
publishing it back turns it on. Same derived-liveness rule ``0007``'s
registrations use, and the reason ``ix_schedules_next_run_at`` needs no leading
status column.

``next_run_at`` is UTC, as every ``DATETIME`` in this schema is, which is what
makes the dispatcher's ``next_run_at <= NOW()`` comparison meaningful.

Schema-only: no data is seeded. Charset/collation are pinned explicitly
(``utf8mb4`` / ``utf8mb4_0900_ai_ci``) rather than inherited from the server
default, matching ``0001`` to ``0007`` — autogenerate omits them every time.

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-18 22:10:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "schedules",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.CHAR(length=26), nullable=False),
        sa.Column("organization_id", mysql.BIGINT(unsigned=True), nullable=False),
        # The trigger node this schedule fires. Version, workflow, and cron
        # expression are all read from the node rather than copied here.
        sa.Column("workflow_node_id", mysql.BIGINT(unsigned=True), nullable=False),
        # UTC. Seeded at publish, advanced past each firing by the dispatcher.
        sa.Column("next_run_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_schedules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        # A workflow that no longer exists has nothing to run, and an orphaned
        # schedule would be a clock firing at nothing.
        sa.ForeignKeyConstraint(
            ["workflow_node_id"],
            ["workflow_nodes.id"],
            name=op.f("fk_schedules_workflow_node_id_workflow_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("public_id", name=op.f("uq_schedules_public_id")),
        # One trigger node fires on one schedule. This unique index also backs
        # the foreign key above, so the column needs no separate index.
        sa.UniqueConstraint("workflow_node_id", name=op.f("uq_schedules_workflow_node_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_index(
        op.f("ix_schedules_organization_id"),
        "schedules",
        ["organization_id"],
        unique=False,
    )
    # The dispatcher's range scan (M6): `WHERE next_run_at <= NOW()`.
    op.create_index(
        "ix_schedules_next_run_at",
        "schedules",
        ["next_run_at"],
        unique=False,
    )


def downgrade() -> None:
    # DROP TABLE removes the table's own indexes and foreign keys, so the
    # explicit drop_index calls Alembic autogenerated are omitted: on MySQL,
    # dropping an index still backing a foreign key fails ("needed in a foreign
    # key constraint"). Same correction as 0001, 0002, 0004, 0005, 0006, 0007.
    op.drop_table("schedules")
