"""refresh_tokens — server-side store for issued refresh tokens

Creates ``refresh_tokens``, the revocation half of ADR-010. Rows hold the
*hash* of an issued refresh token, its ``jti``, and the ``family_id`` linking a
rotation lineage, so a session can be revoked and a replayed token detected.

Schema-only: no data is seeded. Charset/collation are pinned explicitly
(``utf8mb4`` / ``utf8mb4_0900_ai_ci``) rather than inherited from the server
default, matching ``0001`` so the schema stays self-describing.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-27 12:01:57.987279

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "refresh_tokens",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        # The token's `jti` claim, a ULID. Unique: it names exactly one issued
        # token and is the key every refresh lookup uses.
        sa.Column("jti", sa.CHAR(length=26), nullable=False),
        # SHA-256 hex digest — always 64 characters, so CHAR rather than VARCHAR.
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        # Rotation lineage; successors share their predecessor's family_id.
        sa.Column("family_id", sa.CHAR(length=26), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        # NULL means live; set on rotation, logout, or family revocation.
        sa.Column("revoked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name=op.f("uq_refresh_tokens_jti")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)


def downgrade() -> None:
    # DROP TABLE removes the table's own indexes and foreign keys, so the
    # explicit drop_index calls Alembic autogenerated are omitted: on MySQL
    # dropping ix_refresh_tokens_user_id fails while it still backs the foreign
    # key ("needed in a foreign key constraint"). Same correction as 0001.
    op.drop_table("refresh_tokens")
